vote_app/models/candidate.py
from vote_app import db

from werkzeug.security import check_password_hash, generate_password_hash

class CandidateModel(db.Model):
	__tablename__ = 'candidates'

	id = db.Column(db.Integer, primary_key=True, autoincrement=True)
	roll_num = db.Column(db.Integer, nullable=False, unique=True)
	first_name = db.Column(db.String(80), nullable=False)
	last_name = db.Column(db.String(80))
	batch = db.Column(db.Integer, nullable=False)
	course = db.Column(db.Integer, nullable=False)
	department = db.Column(db.Integer, nullable=False)
	post = db.Column(db.Integer, nullable=False)
	pic_path = db.Column(db.String(120), default='images/default.png')
	agenda =  db.Column(db.String(300), default="No agenda")

	def json(self):
		output={
			'id': self.id,
			'roll_num': self.roll_num,
			'first_name': self.first_name,
			'last_name': self.last_name,
			'batch': self.batch,
			'course': self.course,
			'department': self.department,
			'post': self.post,
			'pic_path': self.pic_path,
			'agenda': self.agenda
		}
		return output

	def db_write(self):
		db.session.add(self)
		db.session.commit()

	def db_pop(self):
		db.session.delete(self)
		db.session.commit()

	# First candidate of each post is Nil
	@classmethod
	def null_candidate(cls, post):
		return cls.query.filter_by(post=post).first()

	@classmethod
	def find_all(cls):
		return cls.query.all()

	@classmethod
	def find_by_post(cls, post):
		return cls.query.filter_by(post=post).all()

	@classmethod
	def find_by_id(cls, candidate_id):
		return cls.query.filter_by(id=candidate_id).first()

	@classmethod
	def find_by_rollnum(cls, roll_num):
		return cls.query.filter_by(roll_num=roll_num).first()

	def num_of_post():
		return [posts.post for posts in db.session.query(CandidateModel.post).distinct()]

vote_app/models/user.py
from sqlalchemy.orm import backref
from vote_app import db

from sqlalchemy.ext.hybrid import hybrid_property
from werkzeug.security import check_password_hash, generate_password_hash

class UserModel(db.Model):
	__tablename__ = 'users'

	id = db.Column(db.Integer, primary_key=True, autoincrement=True)
	roll_num = db.Column(db.Integer, nullable=False, unique=True)
	name = db.Column(db.String(80),nullable=False)
	email = db.Column(db.String(120), nullable=False, unique=True)
	_password = db.Column(db.String(), nullable=False)
	admin =  db.Column(db.Integer,default=0)
	votes = db.relationship('VotesModel', backref='voter', lazy=True)
	

	@hybrid_property
	def password(self):
		return self._password

	@password.setter
	def password(self, password_plain):
		self._password = generate_password_hash(password_plain)
	
	def check_password(self, password_plain):
		return check_password_hash(self._password, password_plain)

	# def __init__(self, roll_num,name,password,email,admin=0):
	# 	self.roll_num = roll_num
	# 	self.name = name
	# 	self.email = email
	# 	self.password = password
	# 	self.admin = admin
	
	def json(self):
		output={
			'roll_num': self.roll_num,
			'name': self.name,
			'email': self.email,
		}
		return output
	
	def admin_json(self):
		output={
			'id': self.id,
			'roll_num': self.roll_num,
			'name': self.name,
			'email': self.email,
			'admin':  self.admin
		}
		return output

	def db_write(self):
		db.session.add(self)
		db.session.commit()

	def db_pop(self):
		db.session.delete(self)
		db.session.commit()

	@classmethod
	def find_by_rollnum(cls, roll_num):
		return cls.query.filter_by(roll_num=roll_num).first()

	@classmethod
	def find_by_email(cls, email):
		return cls.query.filter_by(email=email).first()

	@classmethod
	def find_all(cls):
		return cls.query.all()

vote_app/models/votes.py
from sqlalchemy.sql.schema import ForeignKey
from vote_app import db

class VotesModel(db.Model):
	__tablename__ = 'votes'

	id = db.Column(db.Integer, primary_key=True, autoincrement=True)
	roll_num = db.Column(db.Integer, nullable=False, unique=True)
	voter_id = db.Column(db.Integer, ForeignKey('users.id'))
	post_1 = db.Column(db.Integer, nullable=False, default=1)
	post_2 = db.Column(db.Integer, nullable=False, default=1)
 
	def __init__(self, roll_num, voter_id, post_1, post_2):
		self.roll_num = roll_num
		self.post_1 = post_1
		self.post_2 = post_2
		self.voter_id = voter_id

	def db_write(self):
		db.session.add(self)
		db.session.commit()

	def db_pop(self):
		db.session.delete(self)
		db.session.commit()
	
	def json(self):
		output={
			'id': self.id,
			'post_1': self.post_1,
			'post_2':  self.post_2
		}
		return output
	
	def admin_json(self):
		output={
			'id': self.id,
			'roll_num': self.roll_num,
			'voter_id': self.voter_id,
			'post_1': self.post_1,
			'post_2':  self.post_2
		}
		return output


	@classmethod
	def find_by_rollnum(cls, roll_num):
		return cls.query.filter_by(roll_num=roll_num).first()

	@classmethod
	def find_all(cls):
		return cls.query.all()

	@classmethod
	def find_by_candidate(cls, candidate, post):
		if post==1:
			return cls.query.filter_by(post_1=candidate).all()
		elif post==2:
			return cls.query.filter_by(post_2=candidate).all()
		else:
			print("Wierd Should not come here")
			return None

	@classmethod
	def countby_candidate_post(cls, candidate, post):

		if post==1:
			count = VotesModel.query.filter_by(post_1=candidate).count()
		elif post==2:
			count = VotesModel.query.filter_by(post_2=candidate).count()	
		else:
			count = -1
			print("Wierd Should not come here")
		return count

vote_app/ui_paths/choose/forms.py
from flask_wtf import FlaskForm
from wtforms.fields import SelectField, SubmitField


class VoteForm(FlaskForm):
    post1_choice = SelectField('Post 1: President ')
    post2_choice = SelectField('Post 2: Vice-President ')
    submit_button = SubmitField('Vote')

vote_app/__init__.py
import redis


import redis
from flask import Flask
from apispec import APISpec
from apispec.ext.marshmallow import MarshmallowPlugin
from webargs.flaskparser import use_args, use_kwargs, parser, abort

from .runtime.extensions import db, toolbar, jwt, api, docs
from .runtime.config import config_by_name
from .resources.user import User, UserList, UserLogout, UserSingup, UserLogin, TokenRefresh
from .resources.candidate import Candidate, CandidateRegister, CandidateList, Post, PostList
from .resources.votes import Vote, VoteList, VoteCount

from flask_jwt_extended import JWTManager

def create_app(config_name):
	app = Flask(__name__)

	with app.app_context():
  
		app.config.from_object(config_by_name[config_name])
		db.init_app(app)
		toolbar.init_app(app)
		
		# jwt.init_app(app)
		JWTManager(app)
		
		# redis databse
		# Setup our redis connection for storing the blocklisted tokens. You will probably
		# want your redis instance configured to persist data to disk, so that a restart
		# does not cause your application to forget that a JWT was revoked.
		app.jwt_redis_blocklist = redis.StrictRedis(
			host=app.config["REDDIS_HOST"], port=app.config["REDIS_PORT"], db=0, decode_responses=True
		)


		# Callback function to check if a JWT exists in the redis blocklist
		@jwt.token_in_blocklist_loader
		def check_if_token_is_revoked(jwt_header, jwt_payload):
			jti = jwt_payload["jti"]
			token_in_redis = app.jwt_redis_blocklist.get(jti)
			return token_in_redis is not None
		
		# The following callbacks are used for customizing jwt response/error messages.
		# The original ones may not be in a very pretty format (opinionated)
		@jwt.expired_token_loader
		def expired_token_callback():
			output = {
				'message': 'The token has expired.',
				'error': 'token_expired'
				}
			return output, 401 # Staus-Unauthorized


		@jwt.invalid_token_loader
		def invalid_token_callback(error):  # we have to keep the argument here, since it's passed in by the caller internally
			output = {
				'message': 'Signature verification failed.',
				'error': 'invalid_token'
				}
			return output, 401 # Staus-Unauthorized

		@jwt.unauthorized_loader
		def missing_token_callback(error):
			output = {
				"description": "Request does not contain an access token.",
				'error': 'authorization_required'
				}
			return output, 401 # Staus-Unauthorized

		@jwt.needs_fresh_token_loader
		def token_not_fresh_callback():
			output = {
				"description": "The token is not fresh.",
				'error': 'fresh_token_required'
				}
			return output, 401 # Staus-Unauthorized

		@jwt.revoked_token_loader
		def revoked_token_callback(jwt_header, jwt_payload):
			output = {
				"description": "The token has been revoked.",
				'error': 'token_revoked'
				}
			return output, 401 # Staus-Unauthorized

		# Define API's endpoints

		# User API endpoints
		api.add_resource(UserList,'/users')
		api.add_resource(User, '/user/<int:roll_num>')
		api.add_resource(UserSingup, '/signup')
		api.add_resource(UserLogin, '/login')
		api.add_resource(UserLogout, '/logout')
		api.add_resource(TokenRefresh, '/refresh')

		# Candidate API endpoints
		api.add_resource(Post,'/post/<int:post_num>')
		api.add_resource(PostList,'/posts')
		api.add_resource(Candidate,'/candidate/<int:candidate_id>')
		api.add_resource(CandidateRegister,'/reg_candidate')
		api.add_resource(CandidateList, '/candidates')

		# Vote API
		api.add_resource(Vote,'/vote')
		api.add_resource(VoteList,'/votes')
		api.add_resource(VoteCount,'/count')	
		
		api.init_app(app)

		app.config.update({
			'APISPEC_SPEC': APISpec(
				title="Vote System",
				version='v1',
				plugins=[MarshmallowPlugin()],
				openapi_version='2.0.0'
			),
			'APISPEC_SWAGGER_URL': '/swagger/',  # URI to access API Doc JSON
			'APISPEC_SWAGGER_UI_URL': '/swagger-ui/'  # URI to access UI of API Doc
		})
		
		docs.init_app(app)
  
		docs.register(UserSingup)
		docs.register(UserLogin)
		docs.register(UserLogout)
		docs.register(TokenRefresh)
		docs.register(UserList)
		docs.register(User)

		docs.register(Post)
		docs.register(PostList)
		docs.register(Candidate)
		docs.register(CandidateRegister)
		docs.register(CandidateList)

		docs.register(Vote)
		docs.register(VoteList)
		docs.register(VoteCount)

		# This error handler is necessary for usage with Flask-RESTful
		@parser.error_handler
		def handle_request_parsing_error(err, req, schema, *, error_status_code, error_headers):
			"""webargs error handler that uses Flask-RESTful's abort function to return
			a JSON error response to the client.
			"""
			abort(error_status_code, errors=err.messages)
		
		# Blueprint For Different Home Views
		from .ui_paths.home import home as home_blueprint
		app.register_blueprint(home_blueprint, url_prefix='/')

		# Blueprint For Different Authetication Views
		from .ui_paths.auth import auth as auth_blueprint
		app.register_blueprint(auth_blueprint, url_prefix='/auth')

		# Blueprint For Different Candidate Views
		from .ui_paths.candidates import candi as candi_blueprint
		app.register_blueprint(candi_blueprint, url_prefix='/candi')

		# Blueprint For Different Vote Views
		from .ui_paths.choose import choose as choose_blueprint
		app.register_blueprint(choose_blueprint, url_prefix='/choose')

		# Blueprint For Different Graph Views
		from .ui_paths.graph import graph as graph_blueprint
		app.register_blueprint(graph_blueprint, url_prefix='/graph')

	return app

vote_app/ui_paths/candidates/__init__.py
from flask import Blueprint

candi = Blueprint('candi', __name__)

from . import views

vote_app/ui_paths/candidates/views.py
from flask import render_template, flash, redirect, url_for, request
import requests
import json

from . import candi
# from .. import db
# from .forms import LoginForm, SignupForm

from flask import current_app

@candi.route("/candidate_view")
def candidate_view():
    candi_post_1 = requests.get('http://localhost:5000/post/1')
    candi1_dict = candi_post_1.json()
    candi_list_post_1 = candi1_dict['candidates']
    
    candi_post_2 = requests.get('http://localhost:5000/post/2')
    candi2_dict = candi_post_2.json()
    candi_list_post_2 = candi2_dict['candidates']
    
    
    return render_template('candidate_view.html', candidates_post_1=candi_list_post_1 ,candidates_post_2=candi_list_post_2)

vote_app/ui_paths/choose/__init__.py
from flask import Blueprint

choose = Blueprint('choose', __name__)

from . import views
from . import forms

vote_app/ui_paths/choose/views.py
import re
from flask import render_template, flash, redirect, url_for, request, jsonify
from flask_jwt_extended.view_decorators import jwt_required
from flask_jwt_extended import jwt_required, get_jwt
import requests


from . import choose
from .forms import VoteForm

@choose.route("/cast_vote", methods=['GET','POST'])
# @jwt_required()
def cast_vote():
	form = VoteForm()
	voted = requests.get('http://localhost:5000/vote')
	if voted is not None:
		if voted.status_code==200:
			flash("Already Casted Your Vote")
			return redirect(url_for("home.index"))

	r1 = requests.get('http://localhost:5000/post/1')
	r2 = requests.get('http://localhost:5000/post/2')
	if r1.status_code==200 and r2.status_code==200:
		r1_dict=r1.json()
		post1_candidates = r1_dict['candidates']
		post1_options=[]
		for post1_candi in post1_candidates:
			post1_options.append((post1_candi['id'],'{}: {} {}'.format(post1_candi['roll_num'],post1_candi['first_name'],post1_candi['last_name'])))

		r2_dict=r2.json()
		post2_candidates = r2_dict['candidates']
		post2_options=[]
		for post2_candi in post2_candidates:
			post2_options.append((post2_candi['id'],'{}: {} {}'.format(post2_candi['roll_num'],post2_candi['first_name'],post2_candi['last_name'])))

	else:
		flash("Could not find any candidates from DB!")
		redirect(url_for('home.index'))

	form.post1_choice.choices = post1_options
	form.post2_choice.choices = post2_options
	
	if form.validate_on_submit():
		post_1 = request.form.get('post1_choice')
		post_2 = request.form.get('post1_choice')

		label_1 = post1_options[int(post_1)-1]
		label_2 = post2_options[int(post_2)-1]
		data = {"post_1": label_1[0],
				"post_2": label_2[0]
				}
		flash("Post_1: {} and Post_2: {}".format(label_1[1], label_2[1]))
		return redirect(url_for('choose.confirm_vote', vote_data=data))
	
	return render_template("cast_vote.html", form=form)

@choose.route("/confirm_vote", methods=['GET','POST'])
# @jwt_required()
def confirm_vote():
    
	vote_confirm = request.form.get('confirm')
	print(vote_confirm)
	if vote_confirm!=None and vote_confirm!='':
		if int(vote_confirm)==1:
			vote_data = request.args.get('vote_data')
			r = requests.post('http://localhost:5000/vote',json=vote_data,
                      headers={'Content-Type': 'application/json'})
			if r.status_code==200:
				flash("Vote Uploaded")
			else:
				flash("Vote Invalid")
		else:
			flash("Vote Cancelled")

		return redirect(url_for('home.index'))

	return render_template('confirm_vote.html')

vote_app/ui_paths/graph/__init__.py
from flask import Blueprint

graph = Blueprint('graph', __name__)

from . import views

vote_app/ui_paths/graph/views.py
import requests
from flask import render_template, flash, redirect, url_for, request, jsonify
from flask_jwt_extended.view_decorators import jwt_required
from flask_jwt_extended import jwt_required, get_jwt

from . import graph


@graph.route('/')
def graph():
	count_req_data = {"count_method": "all",
						"method_id": 1}
	r = requests.get('http://localhost:5000/count',json=count_req_data,  
							headers={'Content-Type': 'application/json'})
	c = requests.get('http://localhost:5000/candidates')
	if r.status_code==200 and c.status_code==200:
		
		count_dict=r.json()
		count_votes = count_dict['vote_count']
		post1_votes = count_votes["1"]
		print("Post1: ",post1_votes)
		post2_votes = count_votes["2"]
		print("Post2: ",post2_votes)

		# Mapping candidate id votes to candidate roll number
		# for display purposes
		post1_candi_votes=[]
		post1_candi_rollnum=[]
		post2_candi_votes=[]
		post2_candi_rollnum=[]

		candi_dict=c.json()
		canndidates = candi_dict['candidates']
		candi_name = dict()
		for candi in canndidates:
			if candi['post']==1:
				post1_candi_votes.append(post1_votes[str(candi['id'])])
				post1_candi_rollnum.append(candi['roll_num'])
			else:
				post2_candi_votes.append(post2_votes[str(candi['id'])])
				post2_candi_rollnum.append(candi['roll_num'])
    	
			candi_name[candi['roll_num']]='{} {}'.format(candi['first_name'],candi['last_name'])
		print("Candidates:", canndidates)
		print("Post1 Votes:", post1_candi_votes)
		print("Post2 Votes:", post2_candi_votes)
		

	return render_template('graph.html', post1_labels=post1_candi_rollnum, post1_votes= post1_candi_votes,
                        post2_labels=post2_candi_rollnum, post2_votes= post2_candi_votes,
                        candidate_names = candi_name)

vote_app/ui_paths/home/__init__.py
from flask import Blueprint

home = Blueprint('home', __name__)

from . import views

vote_app/ui_paths/home/views.py
from flask import render_template, request

from flask_jwt_extended import get_jwt_identity, jwt_required, get_jwt
from flask_jwt_extended.utils import get_jwt_header

from . import home


@home.route('/')
@home.route('/index')
@jwt_required(optional=True)
def index():
	logged_in = 0
	admin = 0
	head = get_jwt_header()
	print(head)
	identity = get_jwt_identity()
	print(identity)
	claims = get_jwt()
	print('claims:', claims)
	if len(claims)!=0:
		logged_in = 1
		# If user is admin give ability to register
		if claims['admin_access']==1:
			admin = 1
	print("Logged In: ", logged_in)
	print("Admin: ", admin)
			
	return render_template('index.html', admin=admin, logged_in=logged_in)

vote_app/templates/base.html
<!DOCTYPE html>
<html class="no-js" lang="">
    <head>
        <meta charset="utf-8">
        <title>{% block title %}{% endblock %}</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        {% block styles %}
            <link rel="stylesheet" href="{{ url_for('static', filename='css/normalize.min.css') }}">
            <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
        {% endblock %}

    </head>
    <body>

        <div class="header-container">
            <header class="wrapper clearfix">
                <a href="{{ url_for('home.index') }}"><h1 class="title">Vote Sys</h1></a>
                <nav>
                    <ul>
                        <li><a href="/swagger-ui">Swagger UI</a></li>
                        <li><a href="{{ url_for('graph.graph') }}">Vote Count</a></li>
                        <li><a href="{{ url_for('candi.candidate_view') }}">Candidates</a></li>
                        {% if logged_in==1 %}
                            <li><a href="{{ url_for('choose.cast_vote') }}">Vote Now</a></li>
                            <li><a href="{{ url_for('auth.user_logout') }}">Log out</a></li>
                        {% else %}
                            <li><a href="{{ url_for('auth.user_login') }}">Login</a></li>
                            <li><a href="{{ url_for('auth.register') }}">Sign Up</a></li>
                        {% endif %}
                    </ul>
                </nav>
            </header>
        </div>

        <div class="main-container">
            <div class="main wrapper clearfix">
                <article class="flashes">
                    {% with messages = get_flashed_messages() %}
                      {% if messages %}
                        <ul>
                        {% for message in messages %}
                          <li>{{ message }}</li>
                        {% endfor %}
                        </ul>
                      {% endif %}
                    {% endwith %}
                </article>

                {%  block content %}
                {%  endblock %}

            </div> <!-- #main -->
        </div> <!-- #main-container -->

        <div class="footer-container">
            <footer class="wrapper">
                <p>Vote System</p>
            </footer>
        </div>
        
        
        
        {% block scripts %}
        {% endblock %}
    </body>
</html>

vote_app/templates/candidate_view.html
{% extends "base.html" %}
{% from "gallery_macros.html" import render_candidate %}

{% block title %}
Vote Sys -- Login
{%  endblock %}

{% block content %}
	<section>
		<h1>Post 1- President: </h1>
		<br>
		<div class="gallery">
			{% for cur_candi in candidates_post_1 %}
				{{ render_candidate(cur_candi) }}
			{% endfor %}
		</div>
		<br>
		<br>
		<h1>Post-2 President: </h1>
		<br>
		<div class="gallery">
			{% for cur_candi in candidates_post_2 %}
				{{ render_candidate(cur_candi) }}
			{% endfor %}
		</div>
	</section>
{% endblock %}

{% block sidebar %}
{% endblock %}

vote_app/templates/cast_vote.html
{% extends "base.html" %}
{% from "form_macros.html" import render_field %}

{% block title %}
Vote Sys -- Login
{%  endblock %}

{% block content %}
    <section>
        <h1 style="clear: both">Please login</h1>
        <form action="" method="post">
            {{form.hidden_tag()}}
            <table>
                {{ render_field(form.post1_choice) }}
                {{ render_field(form.post2_choice) }}
                {{ render_field(form.submit_button) }}
            </table>
        </form>
    </section>
{% endblock %}

{% block sidebar %}
{% endblock %}

vote_app/templates/confirm_vote.html
{% extends "base.html" %}
{% from "form_macros.html" import render_field %}

{% block title %}
Vote Sys -- Login
{%  endblock %}

{% block content %}
    <section>
        <h1 style="clear: both">Are you sure of your vote?</h1>
        <form role="form" method='POST' action="">
            <button type="submit" name="confirm" value=1 class="btn btn-primary">YES</button>
            <button type="submit" name="confirm" value=0 class="btn btn-primary">No</button>
        </form>
    </section>
{% endblock %}

{% block sidebar %}
{% endblock %}

vote_app/templates/form_macros.html
{% macro render_field(field) %}
    <tr {% if field.errors %} class="error" {% endif %}>
        <td>{{ field.label }}</td>
        <td>{{ field(**kwargs)|safe }}</td>
    </tr>
    <tr class="error" >
        <td></td>
        <td>
            <ul>
                {% for error in field.errors %}
                    <li>{{ error }}</li>
                {% endfor %}
            </ul>
        </td>
    </tr>
{% endmacro %}

vote_app/templates/gallery_macros.html
{% macro render_candidate(candi) %}
    <div class="item">
        <img src=  {{ url_for('static',filename=candi['pic_path'])}} class="pic">
        <div class="content">
        <h3 id="name">Name: {{ candi['first_name'] }} {{ candi['last_name'] }}</h3>
        <h2 id="rollno">Roll Number: {{ candi['roll_num'] }}</h2>
        <br>
        <div id="batch">Batch: {{ candi['batch'] }}</div>
        <h2>Course: {{ candi['course'] }}</h2>
        <h2>Department: {{ candi['department'] }}</h2>
        <p id="agenda">Agenda: {{ candi['agenda'] }}</p>
        </div>
    </div>
{% endmacro %}

vote_app/templates/graph.html
{% extends "base.html" %}

{% block title %}
Voting -- Dashboard
{%  endblock %}

{% block styles %}
{{ super() }}

<script src="https://cdn.jsdelivr.net/momentjs/2.9.0/moment.min.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.4.0/Chart.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.2.1/Chart.bundle.min.js"></script>

{% endblock %}

{% block content %}


<!-- Display Graph Post1 Graph-->
<article class="graph_display">
  <p>
  {% for roll_num in post1_labels %}
    {{ roll_num }}: &nbsp;&nbsp;&nbsp;&nbsp; {{candidate_names[roll_num]}}
    <br>
  {% endfor %}
  </p>
  <div class="chart-container" style="height: 500px; width: 500px">
      <canvas id="Chart1"></canvas>
  </div>

</article>


<!-- Display Graph Post1 Graph-->
<article class="graph_display">
  <p>
  {% for roll_num in post2_labels %}
    {{ roll_num }}: &nbsp;&nbsp;&nbsp;&nbsp; {{candidate_names[roll_num]}}
    <br>
  {% endfor %}
  </p>
  <div class="chart-container" style="height: 500px; width: 500px">
      <canvas id="Chart2"></canvas>
  </div>

</article>


<script>

  
 // define the chart data
  var chartData = {
    labels : [{% for item in post1_labels %}
                {{item}},
              {% endfor %}
             ],
    datasets : [{
        label: 'Votes',
        data : [{% for vote in post1_votes %}
                  {{vote}},
                {% endfor %}]
    }]
  };

  var ctx = document.getElementById("Chart1").getContext("2d");


  // create the chart using the chart canvas
  var Chart1 = new Chart(ctx, {
    type: 'bar',
    data: chartData,
    options: {
      scales: {
		  y:{
			  begginAtZero: true
				}
			}
		},
	});


</script>


<script>

  
 // define the chart data
  var chartData2 = {
    labels : [{% for item in post2_labels %}
                {{item}},
              {% endfor %}
             ],
    datasets : [{
        label: 'Votes',
        data : [{% for vote in post2_votes %}
                  {{vote}},
                {% endfor %}]
    }]
  };

  var ctx = document.getElementById("Chart2").getContext("2d");


  // create the chart using the chart canvas
  var Chart2 = new Chart(ctx, {
    type: 'bar',
    data: chartData2,
    options: {
      scales: {
		  y:{
			  begginAtZero: true
				}
			}
		},
	});


</script>


{% endblock %}


{% block scripts %}
{% endblock %}


{% block sidebar %}
{% endblock %}

vote_app/templates/index.html
{% extends "base.html" %}

{% block title %}
Home Page - Vote System
{%  endblock %}

{% block content %}
    <article>
        <header>
            <h1>Welcome</h1>
            <p>This is a test website for voting by college system.</p>
            </header>
    </article>
{% endblock %}

vote_app/templates/login.html
{% extends "base.html" %}
{% from "form_macros.html" import render_field %}

{% block title %}
Vote Sys -- Login
{%  endblock %}

{% block content %}
    <section>
        <h1 style="clear: both">Please login</h1>
        <form action="" method="post">
            {{form.hidden_tag()}}
            <table>
                {{ render_field(form.roll_num, size=50) }}
                {{ render_field(form.password, size=50) }}
                {{ render_field(form.remember_me) }}
                {{ render_field(form.submit) }}
            </table>
        </form>
    </section>
{% endblock %}

{% block sidebar %}
{% endblock %}

vote_app/templates/register.html
{% extends "base.html" %}
{% from "form_macros.html" import render_field %}

{% block title %}
Vote Sys -- Sigup
{%  endblock %}

{% block content %}
    <section>
        <h1 style="clear: both">Please Register</h1>
        <form action="" method="post">
            {{form.hidden_tag()}}
            <table>
                {{ render_field(form.roll_num, size=50) }}
                {{ render_field(form.name, size=50) }}
				{{ render_field(form.email, size=50) }}
				{{ render_field(form.password, size=50) }}
				{{ render_field(form.password2, size=50) }}
				{{ render_field(form.admin_code, size=50) }}
                {{ render_field(form.submit) }}
            </table>
        </form>
    </section>
{% endblock %}

{% block sidebar %}
{% endblock %}